npmScopes:
  neoxia:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmAuthToken: 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

packageExtensions:
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
